# Generated by Django 6.0 on 2025-12-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_loop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='schedule_type',
            field=models.CharField(choices=[('ALWAYS', 'Always On'), ('SCHEDULED', 'Scheduled')], default='ALWAYS', max_length=10),
        ),
        migrations.AddField(
            model_name='playlist',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SCHEDULED', 'Scheduled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='playlist',
            name='transition_effect',
            field=models.CharField(choices=[('NONE', 'None'), ('FADE', 'Fade'), ('SLIDE', 'Slide')], default='FADE', max_length=10),
        ),
    ]
