# Generated by Django 6.0 on 2026-01-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playlist_end_date_playlist_end_time_playlist_is_loop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for the media', max_length=255, null=True),
        ),
    ]
