# Generated by Django 6.0 on 2026-01-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediaasset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='default_image_duration',
            field=models.PositiveIntegerField(default=10, help_text='Default duration for images in seconds'),
        ),
        migrations.AddField(
            model_name='store',
            name='default_volume',
            field=models.PositiveIntegerField(default=75, help_text='Default volume percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='store',
            name='fallback_logo',
            field=models.URLField(blank=True, help_text='URL to fallback logo image', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='fallback_type',
            field=models.CharField(choices=[('brand_logo', 'Brand Logo'), ('custom_media', 'Custom Media'), ('black_screen', 'Black Screen')], default='brand_logo', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='mute_by_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='transition_effect',
            field=models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('none', 'None')], default='fade', max_length=10),
        ),
    ]
