# Generated by Django 6.0 on 2026-01-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_store_cms_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location of the screen', max_length=255),
        ),
    ]
