# Generated by Django 6.0 on 2026-01-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_screen_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='auto_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, help_text='Internal description of the store'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_beta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to store logo', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='tiktok_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
