# Generated by Django 6.0 on 2026-01-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='api_token',
            field=models.CharField(blank=True, help_text='Token for player API authentication', max_length=64, null=True, unique=True),
        ),
    ]
