# Generated by Django 6.0 on 2026-01-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
