# Generated by Django 6.0 on 2026-01-06 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='store_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.storecontent'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mediaasset'),
        ),
    ]
