# Generated by Django 6.0 on 2026-01-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_playlistitem_store_content_alter_playlistitem_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storecontent',
            name='scheduled_at',
        ),
        migrations.AddField(
            model_name='storecontent',
            name='duration',
            field=models.IntegerField(default=15, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='storecontent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storecontent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storecontent',
            name='target_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contents', to='core.screen'),
        ),
    ]
