# Generated by Django 6.0 on 2026-04-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_storecontent_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media__isnull', False), ('store_content__isnull', True)), models.Q(('media__isnull', True), ('store_content__isnull', False)), _connector='OR'), name='playlistitem_has_exactly_one_content'),
        ),
    ]
